import streamlit as st
import pandas as pd
import numpy as np
import joblib

# --- CONFIGURATION ---
st.set_page_config(
    page_title="GBM Productivity Predictor",
    page_icon="📈",
    layout="wide"
)

# --- LOAD ASSETS ---
@st.cache_resource
def load_assets():
    # Ensure these files are generated by a GradientBoostingClassifier
    model = joblib.load("gbm_model.pkl")
    model_columns = joblib.load("gbm_model_columns.pkl")
    return model, model_columns

try:
    model, model_columns = load_assets()
except FileNotFoundError:
    st.error("Model files not found. Please ensure 'gbm_model.pkl' and 'gbm_model_columns.pkl' are in the directory.")
    st.stop()

# --- UI HEADER ---
st.title("📈 Gradient Boosting: Garment Productivity Forecaster")
st.markdown("""
This tool uses a **Gradient Boosting Classifier** to categorize factory productivity into Low, Moderate, or High tiers based on resource inputs.
""")

# Track validation
form_is_invalid = False

# --- INPUT LAYOUT ---
col1, col2, col3 = st.columns(3)

with col1:
    st.subheader("📅 Contextual Data")
    day = st.selectbox("Day of the Week", ["Monday", "Tuesday", "Wednesday", "Thursday", "Saturday", "Sunday"])
    quarter = st.selectbox("Quarter", ["Quarter1", "Quarter2", "Quarter3", "Quarter4", "Quarter5"])
    dept = st.selectbox("Department", ["Sewing", "Finishing"])
    team = st.slider("Team Number", 1, 12, 1)

with col2:
    st.subheader("⚙️ Operational Inputs")
    wip = st.number_input("Work in Progress (WIP)", min_value=0, value=500)
    if wip > 23122:
        st.error("⚠️ Max WIP: 23,122")
        form_is_invalid = True

    workers = st.number_input("Number of Workers", min_value=2, max_value=90, value=30)
    
    style_change = st.selectbox("Style Changes", ["0", "1", "2"])
    
    smv = st.number_input("SMV (Standard Minute Value)", min_value=2.9, max_value=54.6, value=22.0)

with col3:
    st.subheader("💰 Performance Metrics")
    incentive = st.number_input("Incentive Amount", min_value=0, max_value=3600, value=100)
    overtime = st.slider("Overtime (Scaled)", -2.0, 2.0, 0.0)
    idle_time = st.number_input("Idle Time (Mins)", min_value=0, max_value=300, value=0)
    idle_men = st.number_input("Idle Workers", min_value=0, max_value=45, value=0)

st.divider()

# --- PREDICTION LOGIC ---
if form_is_invalid:
    st.warning("Please correct the validation errors above.")
    st.button("Run Gradient Boosting Analysis", disabled=True, use_container_width=True)
else:
    if st.button("Run Gradient Boosting Analysis", use_container_width=True):
        # 1. Initialize DataFrame with 0s
        input_df = pd.DataFrame(0, index=[0], columns=model_columns)

        # 2. Map Numeric Features (Ensure names match exactly with training columns)
        feature_map = {
            "team": team,
            "smv": smv,
            "wip": wip,
            "incentive": incentive,
            "idle_time": idle_time,
            "idle_men": idle_men,
            "no_of_workers": workers,
            "over_time_scaled": overtime
        }
        
        for col, val in feature_map.items():
            if col in input_df.columns:
                input_df[col] = val

        # 3. Handle Dummy Encoding (One-Hot)
        def set_dummy(category, value):
            col_name = f"{category}_{value}"
            if col_name in input_df.columns:
                input_df[col_name] = 1

        set_dummy("quarter", quarter)
        set_dummy("department", dept.lower())
        set_dummy("day", day)
        set_dummy("no_of_style_change", style_change)

        # 4. Reorder columns to match model training exactly
        input_df = input_df[model_columns]

        # 5. Prediction & Probability
        prediction_idx = model.predict(input_df)[0]
        
        # GBM models usually support predict_proba
        probs = model.predict_proba(input_df)[0] if hasattr(model, "predict_proba") else None
        
        labels = ["Low", "Moderate", "High"]
        result = labels[int(prediction_idx)]

        # --- DISPLAY RESULTS ---
        st.markdown(f"### Result: **{result} Productivity**")
        
        if probs is not None:
            confidence = probs[int(prediction_idx)]
            st.progress(float(confidence))
            st.write(f"Model Confidence: **{confidence:.2%}**")

        if result == "High":
            st.success("The model predicts high efficiency. Current resource allocation is optimal.")
            st.balloons()
        elif result == "Moderate":
            st.info("The model predicts average performance. Room for incentive or WIP adjustment.")
        else:
            st.error("The model predicts a target shortfall. Check Idle Time and Worker count.")

        # Optional: Show raw probabilities in a table
        if probs is not None:
            with st.expander("View Probability Distribution"):
                prob_df = pd.DataFrame([probs], columns=labels)
                st.table(prob_df)
